# Extraction of models from DeciContas.br Dataset

In [1]:
import os
import json
import pymssql

import pandas as pd
import numpy as np

from pprint import pprint
from datetime import datetime, date
from typing import List, Dict, Any, Optional
from langchain_openai import  AzureChatOpenAI, ChatOpenAI
from langchain_core.language_models.chat_models import BaseChatModel
from dotenv import load_dotenv

from sqlalchemy import (
    create_engine, Column, Integer, String, Float, Date, Boolean, Text, JSON
)
from sqlalchemy.orm import declarative_base, sessionmaker, Session
from sqlalchemy.schema import DDL, CheckConstraint
from sqlalchemy.engine import Engine

from tools.schema import (
    NERDecisao,
    Obrigacao,
    Recomendacao,
    ResponsibleChoice
)

from tools.utils import (
    get_decisions_by_year_and_months,
    get_decisions_by_process,
    get_decisions_by_dates,
    run_ner_pipeline_for_dataframe,
    run_obrigacao_pipeline,
    run_recomendacao_pipeline,
    get_connection,
    get_ner_decision
)

load_dotenv()

gpt4turbo = AzureChatOpenAI(
    deployment_name="gpt-4-turbo",
    model_name="gpt-4",
)

'''
gpt4turbo = ChatOpenAI(
    model="gpt-4-turbo",
    temperature=0.0
)
'''

extractor_decisao_gpt4turbo = gpt4turbo.with_structured_output(NERDecisao, include_raw=False, method="json_schema")
extractor_obrigacao_gpt4turbo = gpt4turbo.with_structured_output(
    Obrigacao, include_raw=False, method="json_schema")
extractor_recomendacao_gpt4turbo = gpt4turbo.with_structured_output(
    Recomendacao, include_raw=False, method="json_schema")
extractor_responsible = gpt4turbo.with_structured_output(ResponsibleChoice, include_raw=False, method="json_schema")

c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(

# Run for dates

In [3]:
start_date = date(year=2026, month=1, day=1)
end_date = date(year=2026, month=2, day=11)
df_dec_2026_dates = get_decisions_by_dates(start_date, end_date)

In [5]:
run_ner_pipeline_for_dataframe(
    df=df_dec_2026_dates,
    extractor=extractor_decisao_gpt4turbo,
    model_name="gpt-4-turbo",
    prompt_version="v1",
    run_id=datetime.now().strftime("Extração NER %d/%m/%Y %H:%M:%S")
)

# Run for year and months

In [9]:
#df_dec_2025_1 = get_decisions_by_year_and_months(2025, [10,11,12])
df_dec_2026_1 = get_decisions_by_dates(date(2026,1,13), date(2026,2,26))

In [13]:
df_dec_2026_1['id_voto_pauta'].fillna(0, inplace=True)

C:\Users\05911205424\AppData\Local\Temp\ipykernel_20960\2704298884.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_dec_2026_1['id_voto_pauta'].fillna(0, inplace=True)

In [14]:
run_ner_pipeline_for_dataframe(
    df=df_dec_2026_1,
    extractor=extractor_decisao_gpt4turbo,
    model_name="gpt-4-turbo",
    prompt_version="v1",
    run_id=datetime.now().strftime("Extração NER %d/%m/%Y %H:%M:%S")
)

# Run for processes

In [5]:
processos = [
    "011943/2012",
    "002677/2020",
    "002371/2020",
    "003857/2025",
    "002281/2023",
    "003787/2021",
    "006429/2015",
    "006642/2015",
    "010069/2016",
    "301794/2025",
    "100827/2020",
    "005230/2024",
    "100763/2020",
    "100661/2020",
    "006561/2015",
    "010194/2016",
    "004412/2021",
    "004567/2021",
    "001973/2015",
    "100675/2020",
    "100835/2020",
    "200075/2023",
    "001565/2025",
    "005220/2020",
    "200036/2022",
    "301394/2025",
    "302824/2025",
    "003374/2025",
    "010168/2016",
    "301377/2025",
    "010106/2016",
    "002489/2021",
    "000926/2022",
    "100031/2021",
    "100054/2021",
    "100189/2021",
    "100191/2021",
    "100201/2021",
    "100263/2021",
    "100434/2021",
    "100765/2020",
    "100004/2021",
    "100065/2021",
    "100187/2021",
    "100692/2020",
    "100693/2020",
    "100715/2020",
    "100742/2020",
    "100751/2020",
    "100823/2020",
    "100852/2020",
    "100859/2020",
    "100870/2020",
    "100876/2020",
    "100877/2020",
    "100888/2020",
    "100913/2020",
    "100018/2021",
    "100838/2020",
    "100843/2020",
]

In [6]:
df_processes = get_decisions_by_process(processos)

In [7]:
df_processes

,IdProcesso,processo,orgao_responsavel,id_orgao_responsavel,nome_responsavel,documento_responsavel,tipo_responsavel,id_pessoa,monocratica,codigo_tipo_processo,...,id_processo,interessado,orgao_origem,is_voto_divergente,id_voto_concordado,relatorio,fundamentacao_voto,conclusao,texto_acordao,setor_voto
0,541094,100693/2020,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,308,LUCIA DE FATIMA FARIAS,12990574468,F,54720,0,APO,...,541094,LUCIA DE FATIMA FARIAS ...,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,False,None,1.\tTrata-se da apreciação de legalidade da co...,"6.\tInicialmente, assinalo que ainda não se op...","45.\tDiante do exposto, discordando do posicio...",\r\nDECIDEM os Conselheiros do Tribunal de Con...,GCAED
1,384319,006429/2015,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,406,Raniere Cesar Amâncio da Silva,89784510472,F,9575,0,REL,...,384319,PREF.MUN.LAGOA DE PEDRAS ...,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,False,None,None,None,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR
2,384319,006429/2015,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,406,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,08143026000109,J,12429,0,REL,...,384319,PREF.MUN.LAGOA DE PEDRAS ...,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,False,None,None,None,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR
3,384319,006429/2015,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,406,JANAINA MARIA DE OLIVEIRA SANTOS,06124131447,F,64321,0,REL,...,384319,PREF.MUN.LAGOA DE PEDRAS ...,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,False,None,None,None,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR
4,384489,006642/2015,PREFEITURA MUNICIPAL DE RIACHUELO,451,Mara Lourdes Cavalcanti Machado,04711204482,F,12463,0,REL,...,384489,PREF.MUN.RIACHUELO ...,PREFEITURA MUNICIPAL DE RIACHUELO,False,None,None,None,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,578665,200075/2023,CÂMARA MUNICIPAL DE PASSAGEM,115,CÂMARA MUNICIPAL DE PASSAGEM,24518425000155,J,17536,0,APR,...,578665,GENIVAL LUIZ DOS SANTOS (VEREADOR PRESIDENTE) ...,CÂMARA MUNICIPAL DE PASSAGEM,False,None,Trata-se de processo de Apuração de Responsabi...,I-\tDa Materialidade e da Contagem do Prazo\r\...,"Ante o exposto, divergindo do fundamento do Pa...","\r\nVistos, relatados e discutidos estes autos...",GCPRO
62,607392,005230/2024,PREFEITURA MUNICIPAL DE CAMPO GRANDE,362,FRANCISCO DAS CHAGAS EUFRÁSIO VIEIRA DE MELO,17003458420,F,1203,0,REL,...,607392,PREFEITURA MUNICIPAL DE CAMPO GRANDE ...,TRIBUNAL DE CONTAS DO ESTADO,False,None,Versam os autos sobre as Contas Anuais do Chef...,O exame das contas de governo focaliza a condu...,"Em razão de todo o exposto, em concordância co...","Vistos, relatados e discutidos estes autos, em...",GCGIL
63,607392,005230/2024,PREFEITURA MUNICIPAL DE CAMPO GRANDE,362,PREFEITURA MUNICIPAL DE CAMPO GRANDE,08084014000142,J,12452,0,REL,...,607392,PREFEITURA MUNICIPAL DE CAMPO GRANDE ...,TRIBUNAL DE CONTAS DO ESTADO,False,None,Versam os autos sobre as Contas Anuais do Chef...,O exame das contas de governo focaliza a condu...,"Em razão de todo o exposto, em concordância co...","Vistos, relatados e discutidos estes autos, em...",GCGIL
64,613474,301794/2025,SECRETARIA MUNICIPAL DE SAÚDE DE NATAL,1276,Ana Beatriz Sales Dantas Viegas de Oliveira,10902306480,F,16967,0,DEN,...,613474,JUSTIZ TERCEIRIZAÇÃO DE MÃO DE OBRA EIRELI ...,TRIBUNAL DE CONTAS DO ESTADO,False,None,"Tratam os presentes autos de Comunicação, com ...","Inicialmente, esclareço que os presentes autos...","Diante do exposto, concordando em parte com Co...","\r\nVistos, relatados e discutidos estes autos...",GAMAR
65,613474,301794/2025,SECRETARIA MUNICIPAL DE SAÚDE DE NATAL,1276,Victor Vinicius De Almeida Ferreira,03306422436,F,16754,0,DEN,...,613474,JUSTIZ TERCEIRIZAÇÃO DE MÃO DE OBRA EIRELI ...,TRIBUNAL DE CONTAS DO ESTADO,False,None,"Tratam os presentes autos de Comunicação, com ...","Inicialmente, esclareço que os presentes autos...","Diante do exposto, concordando em parte com Co...","\r\nVistos, relatados e discutidos estes autos...",GAMAR

In [8]:
run_ner_pipeline_for_dataframe(
    df=df_processes,
    extractor=extractor_decisao_gpt4turbo,
    model_name="gpt-4-turbo",
    prompt_version="v1",
    run_id=datetime.now().strftime("Extração NER %d/%m/%Y %H:%M:%S")
)

# Obrigacao and Recomendacao Extraction

In [2]:
run_recomendacao_pipeline(extractor_recomendacao_gpt4turbo, extractor_responsible)

c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(

,id_ner_recomendacao,id_ner_decisao,ordem_obrigacao,descricao_recomendacao,id_processo,processo,orgao_responsavel,id_orgao_responsavel,monocratica,codigo_tipo_processo,...,interessado,orgao_origem,is_voto_divergente,id_voto_concordado,relatorio,fundamentacao_voto,conclusao,texto_acordao,setor_voto,responsaveis
0,1,49,0,essa Corte adotar as providências para eventua...,536612,100433/2020,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,308,0,APO,...,FRANCISCO BERNARDO DE SOUZA ...,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,False,NaN,Trata-se de processo de aposentadoria concedid...,Trata-se concessão de aposentadoria concedida ...,"Diante do exposto, VOTO pelo registro tácito d...",\r\nDECIDEM os Conselheiros do Tribunal de Con...,GCREN,[{'nome_responsavel': 'FRANCISCO BERNARDO DE S...
1,2,221,0,Determinar a expedição de recomendação ao atua...,413817,009819/2016,PREFEITURA MUNICIPAL DE BOM JESUS,351,0,REL,...,PREF.MUN.BOM JESUS ...,PREFEITURA MUNICIPAL DE BOM JESUS,False,NaN,NaN,NaN,Apresento aos Excelentíssimos Srs. Conselheiro...,"\r\nVistos, relatados e discutidos estes autos...",GCAED,[{'nome_responsavel': 'PREFEITURA MUNICIPAL DE...
2,3,226,0,recomendar ao atual Chefe do Poder Executivo d...,607392,005230/2024,PREFEITURA MUNICIPAL DE CAMPO GRANDE,362,0,REL,...,PREFEITURA MUNICIPAL DE CAMPO GRANDE ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,Versam os autos sobre as Contas Anuais do Chef...,O exame das contas de governo focaliza a condu...,"Em razão de todo o exposto, em concordância co...","Vistos, relatados e discutidos estes autos, em...",GCGIL,[{'nome_responsavel': 'PREFEITURA MUNICIPAL DE...
3,4,227,0,recomendação ao atual Chefe do Poder Executivo...,608848,000244/2025,PREFEITURA MUNICIPAL DE PEDRA PRETA,443,0,REL,...,PREFEITURA MUNICIPAL DE PEDRA PRETA ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,NaN,NaN,DECIDE:\r\n\r\na)\tEmitir PARECER PRÉVIO DESFA...,"\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'Luiz Antonio Bandeira d...
4,5,228,0,Expedir recomendação ao Chefe do Poder Executi...,556253,004102/2021,PREFEITURA MUNICIPAL DE CEARÁ-MIRIM,364,0,REL,...,PREFEITURA MUNICIPAL DE CEARÁ-MIRIM ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,NaN,NaN,DECIDE:\r\na)\tEmitir PARECER PRÉVIO DESFAVORÁ...,"\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'ANTONIO HENRIQUE CÂMARA...
5,6,230,0,Expedir recomendação ao atual Chefe do Poder E...,594180,000294/2024,PREFEITURA MUNICIPAL DE ALMINO AFONSO,338,0,REL,...,PREFEITURA MUNICIPAL DE ALMINO AFONSO ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,NaN,NaN,DECIDE:\r\na)\tEmitir PARECER PRÉVIO DESFAVORÁ...,"\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'Jéssica Lourine de Assi...
6,7,233,0,Expedir recomendação ao atual Chefe do Poder E...,556925,004478/2021,PREFEITURA MUNICIPAL DE PEDRA PRETA,443,0,REL,...,PREFEITURA MUNICIPAL DE PEDRA PRETA ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,NaN,NaN,DECIDE:\r\na)\tEmitir PARECER PRÉVIO DESFAVORÁ...,"\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'Luiz Antonio Bandeira d...
7,8,234,0,recomendação ao atual Chefe do Poder Executivo...,527049,002145/2020,PREFEITURA MUNICIPAL DE JUNDIÁ,401,0,REL,...,PREFEITURA MUNICIPAL DE JUNDIÁ ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,NaN,NaN,DECIDE:\r\n\r\na)\tEmitir PARECER PRÉVIO PELA ...,"\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'PREFEITURA MUNICIPAL DE...
8,9,248,0,recomendação ao gestor atual da Prefeitura Mun...,600439,002771/2024,PREFEITURA MUNICIPAL DE SAO TOME,483,0,REP,...,PREFEITURA MUNICIPAL DE SAO TOME ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,1.\tTrata-se de Representação ofertada pela Di...,Da competência deste Tribunal para processar e...,"62.\tDiante do exposto, VOTO de forma prelimin...","\r\nVistos, relatados e discutidos estes autos...",GCAED,[{'nome_responsavel': 'PREFEITURA MUNICIPAL DE...
9,10,261,0,expedição de RECOMENDAÇÕES às SECRETARIA MUNIC...,361597,010680/2014,PREFEITURA MUNICIPAL DE NATAL,422,0,REP,...,MINISTERIO PUBLICO DE CONTAS ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,Autos registrados em 31.jul.2014. Versam sobre...,II.1) Contextualização. O estado de arte proce...,Nos termos do parecer ministerial apensado no ...,"\r\nVistos, relatados e discutidos estes autos...",GAANA,"[{'nome_responsavel': 'Municipio de Natal', 'd..."
10,11,262,0,recomendação ao Chefe do Poder Executivo Munic...,340699,015898/2013,PREFEITURA MUNICIPAL DE TRIUNFO POTIGUAR,493,0,REL,...,PREF.MUN.TRIUNFO POTIGUAR ...,PREFEITURA MUNICIPAL DE TRIUNFO POTIGUAR,False,NaN,NaN,NaN,DECIDE:\r\n\r\na)\tEmitir PARECER PRÉVIO DESFA...,"\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'PREFEITURA MUNICIPAL DE...
11,12,263,0,recomendação ao Chefe do Poder Executivo Munic...,354014,005848/2014,PREFEITURA MUNICIPAL DE LAJES PINTADA,407,0,REL,...,PREF.MUN.LAJES PINTADA ...,PREFEITURA MUNICIPAL DE LAJES PINTADA,False,NaN,NaN,NaN,a)\tEmitir PARECER PRÉVIO DESFAVORÁVEL À APROV...,"\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'LUCIANO DA CUNHA GOMES'...
12,13,269,0,Recomendar ao Chefe do Poder Executivo do Muni...,384348,006444/2015,PREFEITURA MUNICIPAL DE NATAL,422,0,REL,...,PREF.MUN.NATAL ...,PREFEITURA MUNICIPAL DE NATAL,False,NaN,NaN,NaN,1)\tEmitir PARECER PRÉVIO DESFAVORÁVEL À APROV...,"\r\nVistos, relatados e discutidos estes autos...",GCPOT,"[{'nome_responsavel': 'Municipio de Natal', 'd..."
13,14,270,0,Expedir recomendação ao Chefe do Poder Executi...,384459,006620/2015,PREFEITURA MUNICIPAL DE SÃO RAFAEL,480,0,REL,...,PREF.MUN.SÃO RAFAEL ...,PREFEITURA MUNICIPAL DE SÃO RAFAEL,False,NaN,NaN,NaN,a)\tEmitir PARECER PRÉVIO DESFAVORÁVEL À APROV...,"\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'PREFEITURA MUNICIPAL DE...
14,15,271,0,recomendação ao Chefe do Poder Executivo do mu...,384494,006650/2015,PREFEITURA MUNICIPAL DE SERRA DE SÃO BENTO,481,0,REL,...,PREF.MUN.SERRA DE SÃO BENTO ...,PREFEITURA MUNICIPAL DE SERRA DE SÃO BENTO,False,NaN,NaN,NaN,1)\tEmitir PARECER PRÉVIO DESFAVORÁVEL À APROV...,"\r\nVistos, relatados e discutidos estes autos...",GCPOT,[{'nome_responsavel': 'JAUMAR ALVES DA CRUZ JU...
15,16,272,0,Expedir recomendação ao Chefe do Poder Executi...,526584,001989/2020,PREFEITURA MUNICIPAL DE MACAÍBA,411,0,REL,...,PREFEITURA MUNICIPAL DE MACAÍBA ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,NaN,NaN,DECIDE:\r\n\r\na)\tEmitir PARECER PRÉVIO DESFA...,"\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'PREFEITURA MUNICIPAL DE...
16,17,275,0,recomendação ao Chefe do Poder Executivo Munic...,528388,002695/2020,PREFEITURA MUNICIPAL DE ITAÚ,389,0,REL,...,PREFEITURA MUNICIPAL DE ITAÚ ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,NaN,NaN,DECIDE-SE:\r\n\r\na)\tEmitir PARECER PRÉVIO DE...,"\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'Ciro Gustavo Alves Beze...
17,18,276,0,recomendação ao atual gestor do Fundo de Previ...,534302,600229/2020,FUNDO DE PREVIDÊNCIA DE VERA CRUZ,1263,0,APR,...,FUNDO DE PREVIDÊNCIA DE VERA CRUZ ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,I – RELATÓRIO\r\n\r\nTrata-se de processo de a...,II – FUNDAMENTAÇÃO\r\n\r\nA matéria em análise...,"III – CONCLUSÃO\r\n\r\nAnte o exposto, VOTO, a...","\r\nVistos, relatados e discutidos estes autos...",GCGEO,[{'nome_responsavel': 'PREFEITURA MUNICIPAL DE...
18,19,283,0,recomendar ao atual Chefe do Poder Executivo d...,384263,006375/2015,PREFEITURA MUNICIPAL DE CAMPO REDONDO,367,0,REL,...,PREF.MUN.CAMPO REDONDO ...,PREFEITURA MUNICIPAL DE CAMPO REDONDO,False,NaN,Versam os autos sobre as Contas Anuais do Chef...,O exame das contas de governo focaliza a condu...,"Em razão de todo o exposto, em consonância par...","\r\nVistos, relatados e discutidos estes autos...",GCGIL,[{'nome_responsavel': 'PREFEITURA MUNICIPAL DE...
19,20,289,0,recomendar ao Chefe do Poder Executivo do Muni...,414118,010106/2016,PREFEITURA MUNICIPAL DE TIBAU DO SUL,494,0,REL,...,PREF.MUN.TIBAU DO SUL ...,PREFEITURA MUNICIPAL DE TIBAU DO SUL,False,NaN,NaN,NaN,1)\tEmitir PARECER PRÉVIO DESFAVORÁVEL À APROV...,"\r\nVistos, relatados e discutidos estes autos...",GCPOT,[{'nome_responsavel': 'Valdenicio Jose da cost...
20,21,290,0,Recomendar ao Chefe do Poder Executivo do Muni...,414185,010168/2016,PREFEITURA MUNICIPAL DE CARNAÚBA DOS DANTAS,360,0,REL,...,PREF.MUN.CARNAÚBA DOS DANTAS ...,PREFEITURA MUNICIPAL DE CARNAÚBA DOS DANTAS,False,NaN,NaN,NaN,1)\tEmitir PARECER PRÉVIO FAVORÁVEL À APROVAÇÃ...,"\r\nVistos, relatados e discutidos estes autos...",GCPOT,[{'nome_responsavel': 'KLEYTON MEDEIROS DANTAS...
21,22,291,0,RECOMENDAR à Secretaria de Controle Externo (S...,428263,021528/2016,ASSEMBLEIA LEGISLATIVA DO ESTADO DO RN,333,0,AUD,...,ASSEMBLÉIA LEGISLATIVA DO ESTADO DO RN ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,Trata-se de Auditoria de Conformidade na gestã...,"O escopo do Termo de Ajustamento de Gestão, co...",Ante o exposto e em consonância com o Parecer ...,"\r\nVistos, relatados e discutidos estes autos...",GCCTH,[{'nome_responsavel': 'Assembleia Legislativa ...
22,23,303,0,recomendação à azienda pública no sentido de a...,540852,005220/2020,CÂMARA MUNICIPAL DE SÃO GONÇALO DO AMARANTE,147,0,APR,...,CÂMARA MUNICIPAL DE SÃO GONÇALO DO AMARANTE ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,Autos instaurados em 2.dez.2020 (evento 0). Ve...,"2.1) Contextualização. À luz do evento 37, man...",Em face das razões declinadas no excerto prece...,"\r\nVistos, relatados e discutidos estes autos...",GAANA,[{'nome_responsavel': 'JAIME CALADO PEREIRA DO...
23,24,315,0,expedição de recomendação à atual gestão da lo...,560775,200036/2022,PREFEITURA MUNICIPAL DE CANGUARETAMA,356,0,APR,...,JOÃO WILSON DE ANDRADE RIBEIRO FILHO ...,PREFEITURA MUNICIPAL DE CANGUARETAMA,False,NaN,Autos instaurados em 14.mar.2022. Tratam de ap...,"2.1) Contextualização. No evento 2, o corpo in...","Em face do documentado nos eventos 2, 64, 71, ...","\r\nVistos, relatados e discutidos estes autos...",GAANA,[{'nome_responsavel': 'MARIA ERENIR FREITAS DE...
24,25,316,0,EXPEDIÇÃO DE RECOMENDAÇÃO para que a gestão at...,560871,000926/2022,PREFEITURA MUNICIPAL DE SANTA MARIA,470,0,ACO,...,PREFEITURA MUNICIPAL DE SANTA MARIA ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,\tTrata-se de Representação com pedido cautela...,"Inicialmente, cumpre ressaltar que restou comp...","Diante do exposto, concordando integralmente c...","\r\nVistos, relatados e discutidos estes autos...",GAMAR,[{'nome_responsavel': 'Prefeitura Municipal de...
25,26,319,0,recomendação ao atual gestor da Câmara Municip...,578665,200075/2023,CÂMARA MUNICIPAL DE PASSAGEM,115,0,APR,...,GENIVAL LUIZ DOS SANTOS (VEREADOR PRESIDENTE) ...,CÂMARA MUNICIPAL DE PASSAGEM,False,NaN,Trata-se de processo de Apuração de Responsabi...,I-\tDa Materialidade e da Contagem do Prazo\r\...,"Ante o exposto, divergindo do fundamento do Pa...","\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'CÂMARA MUNICIPAL DE PAS...
26,27,328,0,"recomendação ao Chefe do Poder Executivo, para...",384319,006429/2015,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,406,0,REL,...,PREF.MUN.LAGOA DE PEDRAS ...,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,False,NaN,NaN,NaN,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR,[{'nome_responsavel': 'JANAINA MARIA DE OLIVEI...
27,28,329,0,"recomendação ao Chefe do Poder Executivo, para...",384489,006642/2015,PREFEITURA MUNICIPAL DE RIACHUELO,451,0,REL,...,PREF.MUN.RIACHUELO ...,PREFEITURA MUNICIPAL DE RIACHUELO,False,NaN,NaN,NaN,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR,[{'nome_responsavel': 'Mara Lourdes Cavalcanti...
28,29,330,0,recomendar ao atual e aos seguintes Chefes do ...,384408,006561/2015,PREFEITURA MUNICIPAL DE PASSA E FICA,438,0,REL,...,PREF.MUN.PASSA E FICA ...,PREFEITURA MUNICIPAL DE PASSA E FICA,False,NaN,NaN,NaN,"DECIDE, emitir PARECER PRÉVIO DESFAVORÁVEL À A...","\r\nVistos, relatados e discutidos estes autos...",GCREN,"[{'nome_responsavel': 'DAVID DA SILVA ARAÚJO',..."
29,30,332,0,"recomendação ao Chefe do Poder Executivo, para...",414078,010069/2016,PREFEITURA MUNICIPAL DE OURO BRANCO,425,0,REL,...,PREF.MUN.OURO BRANCO ...,PREFEITURA MUNICIPAL DE OURO BRANCO,False,NaN,NaN,NaN,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR,[{'nome_responsavel': 'MARIA DE FÁTIMA ARAÚJO ...
30,31,333,0,recomendar ao atual Chefe do Poder Executivo d...,414207,010194/2016,PREFEITURA MUNICIPAL DE SÃO RAFAEL,480,0,REL,...,PREF.MUN.SÃO RAFAEL ...,PREFEITURA MUNICIPAL DE SÃO RAFAEL,False,NaN,Versam os autos sobre as Contas Anuais do Chef...,1. DA AUSÊNCIA DE INTERVENÇÃO MINISTERIAL \r\n...,"Em razão de todo o exposto, em consonância par...","\r\nVistos, relatados e discutidos estes autos...",GCGIL,[{'nome_responsavel': 'PREFEITURA MUNICIPAL DE...
31,32,334,0,recomendação ao atual Chefe do Poder Executivo...,527879,002371/2020,PREFEITURA MUNICIPAL DE PASSA E FICA,438,0,REL,...,PREFEITURA MUNICIPAL DE PASSA E FICA ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,NaN,NaN,DECIDE:\r\n\r\na)\tEmitir PARECER PRÉVIO DESFA...,"\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'FLAVIANO CORREIA LISBOA...
32,33,335,0,recomendação ao atual Chefe do Poder Executivo...,528250,002677/2020,PREFEITURA MUNICIPAL DE ANGICOS,341,0,REL,...,PREFEITURA MUNICIPAL DE ANGICOS ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,NaN,NaN,DECIDE:\r\n\r\na)\tEmitir PARECER PRÉVIO DESFA...,"\r\nVistos, relatados e discutidos estes autos...",GCPRO,[{'nome_responsavel': 'PREFEITURA MUNICIPAL DE...
33,34,337,0,"recomendação ao Chefe do Poder Executivo, para...",555896,003787/2021,PREFEITURA MUNICIPAL DE ACARI,337,0,REL,...,PREFEITURA MUNICIPAL DE ACARI ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,NaN,NaN,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR,[{'nome_responsavel': 'PREFEITURA MUNICIPAL DE...
34,35,349,0,recomendação ao órgão por meio da atual gestor...,325393,701100/2013,PREFEITURA MUNICIPAL DE JARDIM DE ANGICOS,393,0,LRF,...,PREF.MUN.JARDIM DE ANGICOS ...,PREFEITURA MUNICIPAL DE JARDIM DE ANGICOS,False,NaN,1.\tTrata-se da análise da gestão fiscal da Pr...,Da competência do TCE para processar e julgar ...,"62.\tDo exposto, VOTO de forma preliminar: a) ...","\r\nVistos, relatados e discutidos estes autos...",GCAED,[{'nome_responsavel': 'SUELY FONSECA BEZERRA D...
35,36,358,0,Recomendar ao Chefe do Poder Executivo do muni...,414133,010122/2016,PREFEITURA MUNICIPAL DE TAIPU,485,0,REL,...,PREF.MUN.TAIPU ...,PREFEITURA MUNICIPAL DE TAIPU,False,NaN,NaN,NaN,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR,[{'nome_responsavel': 'Ariosvaldo Bandeira Jun...
36,37,359,0,recomendar ao atual Chefe do Poder Executivo d...,414177,010157/2016,PREFEITURA MUNICIPAL DE CAMPO GRANDE,362,0,REL,...,PREF.MUN.CAMPO GRANDE ...,PREFEITURA MUNICIPAL DE CAMPO GRANDE,False,NaN,Versam os autos sobre as Contas Anuais do Chef...,1. DA AUSÊNCIA DE INTERVENÇÃO MINISTERIAL \r\n...,"Em razão de todo o exposto, em consonância par...","\r\nVistos, relatados e discutidos estes autos...",GCGIL,[{'nome_responsavel': 'FRANCISCO DAS CHAGAS EU...
37,38,360,0,Recomendar ao atual Chefe do Poder Executivo d...,414216,010203/2016,PREFEITURA MUNICIPAL DE MARTINS,414,0,REL,...,PREF.MUN.MARTINS ...,PREFEITURA MUNICIPAL DE MARTINS,False,NaN,Versam os autos sobre as Contas Anuais do Chef...,1. DA AUSÊNCIA DE INTERVENÇÃO MINISTERIAL \r\n...,"Em razão de todo o exposto, em consonância par...","\r\nVistos, relatados e discutidos estes autos...",GCGIL,[{'nome_responsavel': 'OLGA CHAVES FERNANDES D...
38,39,360,1,Recomendar ao atual Chefe do Poder Legislativo...,414216,010203/2016,PREFEITURA MUNICIPAL DE MARTINS,414,0,REL,...,PREF.MUN.MARTINS ...,PREFEITURA MUNICIPAL DE MARTINS,False,NaN,Versam os autos sobre as Contas Anuais do Chef...,1. DA AUSÊNCIA DE INTERVENÇÃO MINISTERIAL \r\n...,"Em razão de todo o exposto, em consonância par...","\r\nVistos, relatados e discutidos estes autos...",GCGIL,[{'nome_responsavel': 'OLGA CHAVES FERNANDES D...
39,40,361,0,Recomendação ao atual Chefe do Poder Executivo...,414234,010221/2016,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,406,0,REL,...,PREF.MUN.LAGOA DE PEDRAS ...,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,False,NaN,Versam os autos sobre as Contas Anuais do Chef...,1. DA AUSÊNCIA DE INTERVENÇÃO MINISTERIAL \r\n...,"Em razão de todo o exposto, em consonância par...","\r\nVistos, relatados e discutidos estes autos...",GCGIL,[{'nome_responsavel': 'Raniere Cesar Amâncio d...
40,41,362,0,Recomendar ao Chefe do Poder Executivo do Muni...,414283,010265/2016,PREFEITURA MUNICIPAL DE SERRA DE SÃO BENTO,481,0,REL,...,PREF.MUN.SERRA DE SÃO BENTO ...,PREFEITURA MUNICIPAL DE SERRA DE SÃO BENTO,False,NaN,NaN,NaN,1)\tEmitir PARECER PRÉVIO DESFAVORÁVEL À APROV...,"\r\nVistos, relatados e discutidos estes autos...",GCPOT,[{'nome_responsavel': 'EMANUEL FAUSTINO DA SIL...
41,42,363,0,Recomendar ao Chefe do Poder Executivo do Muni...,414334,010326/2016,PREFEITURA MUNICIPAL DE GUAMARÉ,384,0,REL,...,PREF.MUN.GUAMARÉ ...,PREFEITURA MUNICIPAL DE GUAMARÉ,False,NaN,NaN,NaN,1)\tEmitir PARECER PRÉVIO DESFAVORÁVEL À APROV...,"\r\nVistos, relatados e discutidos estes autos...",GCPOT,[{'nome_responsavel': 'HÉLIO WILLAMY MIRANDA D...
42,43,364,0,Recomendar ao Chefe do Poder Executivo do Muni...,414374,010353/2016,PREFEITURA MUNICIPAL DE SANTA MARIA,470,0,REL,...,PREF.MUN.SANTA MARIA ...,PREFEITURA MUNICIPAL DE SANTA MARIA,False,NaN,NaN,NaN,1)\tEmitir PARECER PRÉVIO FAVORÁVEL À APROVAÇÃ...,"\r\nVistos, relatados e discutidos estes autos...",GCPOT,[{'nome_responsavel': 'CELINA AMÉLIA CÂMARA DE...
43,44,366,0,RECOMENDAÇÃO aos jurisdicionados (Câmara Munic...,421580,016548/2016,CÂMARA MUNICIPAL DE MESSIAS TARGINO,103,0,REP,...,CAM.MUN.MESSIAS TARGINO ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,Versam os presentes autos de Representação fo...,"De início, faz-se necessário destacar que a pr...","Ante o exposto, em consonância com o Corpo Téc...","\r\nVistos, relatados e discutidos estes autos...",GCREN,[{'nome_responsavel': 'Francimar Ferreira da S...
44,45,369,0,recomendação à azienda pública no sentido de a...,495557,000406/2019,PREFEITURA MUNICIPAL DE SÃO FERNANDO,462,0,APR,...,PREFEITURA MUNICIPAL DE SÃO FERNANDO ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,Autos instaurados em 24.jan.2019 (evento 0). V...,2.1) Contextualização. O presente foi instaura...,Em face das razões declinadas no excerto prece...,"\r\nVistos, relatados e discutidos estes autos...",GAANA,[{'nome_responsavel': 'GENILSON MEDEIROS MAIA'...
45,46,371,0,expedição de recomendação à azienda pública no...,511914,006410/2019,PREFEITURA MUNICIPAL DE JAÇANÃ,390,0,APR,...,PREFEITURA MUNICIPAL DE JAÇANÃ ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,Autos instaurados no TCE/RN em 9.out.2019. Ver...,2.1) Contextualização: trata-se de apuração de...,Em face das razões declinadas no excerto prece...,"\r\nVistos, relatados e discutidos estes autos...",GAANA,[{'nome_responsavel': 'ESDRAS FERNANDES FARIAS...
46,47,376,0,Recomendar ao Chefe do Poder Executivo do Muni...,528027,002474/2020,PREFEITURA MUNICIPAL DE IPANGUAÇU,386,0,REL,...,PREFEITURA MUNICIPAL DE IPANGUAÇU ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,NaN,NaN,1)\tEmitir PARECER PRÉVIO DESFAVORÁVEL À APROV...,"\r\nVistos, relatados e discutidos estes autos...",GCPOT,[{'nome_responsavel': 'LEONARDO DA SILVA OLIVE...

In [ ]:
run_obrigacao_pipeline(extractor_obrigacao_gpt4turbo, extractor_responsible)