# Extraction of models from DeciContas.br Dataset

In [1]:
import os
import json
import pymssql

import pandas as pd
import numpy as np

from pprint import pprint
from datetime import datetime, date
from typing import List, Dict, Any, Optional
from langchain_openai import  AzureChatOpenAI, ChatOpenAI
from langchain_core.language_models.chat_models import BaseChatModel
from dotenv import load_dotenv

from sqlalchemy import (
    create_engine, Column, Integer, String, Float, Date, Boolean, Text, JSON
)
from sqlalchemy.orm import declarative_base, sessionmaker, Session
from sqlalchemy.schema import DDL, CheckConstraint
from sqlalchemy.engine import Engine

from tools.schema import (
    NERDecisao,
    Obrigacao,
    Recomendacao,
    ResponsibleChoice
)

from tools.utils import (
    get_decisions_by_year_and_months,
    get_decisions_by_process,
    get_decisions_by_dates,
    run_ner_pipeline_for_dataframe,
    run_obrigacao_pipeline,
    get_connection
)

load_dotenv()

gpt4turbo = AzureChatOpenAI(
    deployment_name="gpt-4-turbo",
    model_name="gpt-4",
)

'''
gpt4turbo = ChatOpenAI(
    model="gpt-4-turbo",
    temperature=0.0
)
'''

extractor_decisao_gpt4turbo = gpt4turbo.with_structured_output(NERDecisao, include_raw=False, method="json_schema")
extractor_obrigacao_gpt4turbo = gpt4turbo.with_structured_output(
    Obrigacao, include_raw=False, method="json_schema")
extractor_recomendacao_gpt4turbo = gpt4turbo.with_structured_output(
    Recomendacao, include_raw=False, method="json_schema")
extractor_responsible = gpt4turbo.with_structured_output(ResponsibleChoice, include_raw=False, method="json_schema")

c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(

# Run for dates

In [3]:
start_date = date(year=2025, month=12, day=4)
end_date = date(year=2026, month=1, day=7)
df_dec_2025_dates = get_decisions_by_dates(start_date, end_date)

In [4]:
run_ner_pipeline_for_dataframe(
    df=df_dec_2025_dates,
    extractor=extractor_decisao_gpt4turbo,
    model_name="gpt-4-turbo",
    prompt_version="v1",
    run_id=datetime.now().strftime("Extração NER %d/%m/%Y %H:%M:%S")
)

# Run for year and months

In [3]:
#df_dec_2025_1 = get_decisions_by_year_and_months(2025, [10,11,12])
df_dec_2026_1 = get_decisions_by_dates(date(2026,1,1), date(2026,1,13))

In [4]:
df_dec_2026_1

Empty DataFrame
Columns: [IdProcesso, processo, orgao_responsavel, id_orgao_responsavel, nome_responsavel, documento_responsavel, tipo_responsavel, id_pessoa, monocratica, codigo_tipo_processo, descricao, tipo_voto, voto_escolhido, id_composicao_pauta, numero_sessao, ano_sessao, data_sessao, data_encerramento_sessao, numero_resultado, ano_resultado, resultado_tipo, id_voto_pauta, id_voto_decisao, ementa, assunto, numero_processo, ano_processo, id_processo, interessado, orgao_origem, is_voto_divergente, id_voto_concordado, relatorio, fundamentacao_voto, conclusao, texto_acordao, setor_voto]
Index: []

[0 rows x 37 columns]

In [ ]:
run_ner_pipeline_for_dataframe(
    df=df_dec_2026_1,
    extractor=extractor_decisao_gpt4turbo,
    model_name="gpt-4-turbo",
    prompt_version="v1",
    run_id=datetime.now().strftime("Extração NER %d/%m/%Y %H:%M:%S")
)

# Run for processes

In [5]:
processos = [
    "011943/2012",
    "002677/2020",
    "002371/2020",
    "003857/2025",
    "002281/2023",
    "003787/2021",
    "006429/2015",
    "006642/2015",
    "010069/2016",
    "301794/2025",
    "100827/2020",
    "005230/2024",
    "100763/2020",
    "100661/2020",
    "006561/2015",
    "010194/2016",
    "004412/2021",
    "004567/2021",
    "001973/2015",
    "100675/2020",
    "100835/2020",
    "200075/2023",
    "001565/2025",
    "005220/2020",
    "200036/2022",
    "301394/2025",
    "302824/2025",
    "003374/2025",
    "010168/2016",
    "301377/2025",
    "010106/2016",
    "002489/2021",
    "000926/2022",
    "100031/2021",
    "100054/2021",
    "100189/2021",
    "100191/2021",
    "100201/2021",
    "100263/2021",
    "100434/2021",
    "100765/2020",
    "100004/2021",
    "100065/2021",
    "100187/2021",
    "100692/2020",
    "100693/2020",
    "100715/2020",
    "100742/2020",
    "100751/2020",
    "100823/2020",
    "100852/2020",
    "100859/2020",
    "100870/2020",
    "100876/2020",
    "100877/2020",
    "100888/2020",
    "100913/2020",
    "100018/2021",
    "100838/2020",
    "100843/2020",
]

In [6]:
df_processes = get_decisions_by_process(processos)

In [7]:
df_processes

,IdProcesso,processo,orgao_responsavel,id_orgao_responsavel,nome_responsavel,documento_responsavel,tipo_responsavel,id_pessoa,monocratica,codigo_tipo_processo,...,id_processo,interessado,orgao_origem,is_voto_divergente,id_voto_concordado,relatorio,fundamentacao_voto,conclusao,texto_acordao,setor_voto
0,541094,100693/2020,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,308,LUCIA DE FATIMA FARIAS,12990574468,F,54720,0,APO,...,541094,LUCIA DE FATIMA FARIAS ...,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,False,None,1.\tTrata-se da apreciação de legalidade da co...,"6.\tInicialmente, assinalo que ainda não se op...","45.\tDiante do exposto, discordando do posicio...",\r\nDECIDEM os Conselheiros do Tribunal de Con...,GCAED
1,384319,006429/2015,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,406,Raniere Cesar Amâncio da Silva,89784510472,F,9575,0,REL,...,384319,PREF.MUN.LAGOA DE PEDRAS ...,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,False,None,None,None,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR
2,384319,006429/2015,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,406,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,08143026000109,J,12429,0,REL,...,384319,PREF.MUN.LAGOA DE PEDRAS ...,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,False,None,None,None,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR
3,384319,006429/2015,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,406,JANAINA MARIA DE OLIVEIRA SANTOS,06124131447,F,64321,0,REL,...,384319,PREF.MUN.LAGOA DE PEDRAS ...,PREFEITURA MUNICIPAL DE LAGOA DE PEDRAS,False,None,None,None,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR
4,384489,006642/2015,PREFEITURA MUNICIPAL DE RIACHUELO,451,Mara Lourdes Cavalcanti Machado,04711204482,F,12463,0,REL,...,384489,PREF.MUN.RIACHUELO ...,PREFEITURA MUNICIPAL DE RIACHUELO,False,None,None,None,CONSIDERANDO os poderes a mim conferidos pela ...,"\r\nVistos, relatados e discutidos estes autos...",GAMAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,578665,200075/2023,CÂMARA MUNICIPAL DE PASSAGEM,115,CÂMARA MUNICIPAL DE PASSAGEM,24518425000155,J,17536,0,APR,...,578665,GENIVAL LUIZ DOS SANTOS (VEREADOR PRESIDENTE) ...,CÂMARA MUNICIPAL DE PASSAGEM,False,None,Trata-se de processo de Apuração de Responsabi...,I-\tDa Materialidade e da Contagem do Prazo\r\...,"Ante o exposto, divergindo do fundamento do Pa...","\r\nVistos, relatados e discutidos estes autos...",GCPRO
62,607392,005230/2024,PREFEITURA MUNICIPAL DE CAMPO GRANDE,362,FRANCISCO DAS CHAGAS EUFRÁSIO VIEIRA DE MELO,17003458420,F,1203,0,REL,...,607392,PREFEITURA MUNICIPAL DE CAMPO GRANDE ...,TRIBUNAL DE CONTAS DO ESTADO,False,None,Versam os autos sobre as Contas Anuais do Chef...,O exame das contas de governo focaliza a condu...,"Em razão de todo o exposto, em concordância co...","Vistos, relatados e discutidos estes autos, em...",GCGIL
63,607392,005230/2024,PREFEITURA MUNICIPAL DE CAMPO GRANDE,362,PREFEITURA MUNICIPAL DE CAMPO GRANDE,08084014000142,J,12452,0,REL,...,607392,PREFEITURA MUNICIPAL DE CAMPO GRANDE ...,TRIBUNAL DE CONTAS DO ESTADO,False,None,Versam os autos sobre as Contas Anuais do Chef...,O exame das contas de governo focaliza a condu...,"Em razão de todo o exposto, em concordância co...","Vistos, relatados e discutidos estes autos, em...",GCGIL
64,613474,301794/2025,SECRETARIA MUNICIPAL DE SAÚDE DE NATAL,1276,Ana Beatriz Sales Dantas Viegas de Oliveira,10902306480,F,16967,0,DEN,...,613474,JUSTIZ TERCEIRIZAÇÃO DE MÃO DE OBRA EIRELI ...,TRIBUNAL DE CONTAS DO ESTADO,False,None,"Tratam os presentes autos de Comunicação, com ...","Inicialmente, esclareço que os presentes autos...","Diante do exposto, concordando em parte com Co...","\r\nVistos, relatados e discutidos estes autos...",GAMAR
65,613474,301794/2025,SECRETARIA MUNICIPAL DE SAÚDE DE NATAL,1276,Victor Vinicius De Almeida Ferreira,03306422436,F,16754,0,DEN,...,613474,JUSTIZ TERCEIRIZAÇÃO DE MÃO DE OBRA EIRELI ...,TRIBUNAL DE CONTAS DO ESTADO,False,None,"Tratam os presentes autos de Comunicação, com ...","Inicialmente, esclareço que os presentes autos...","Diante do exposto, concordando em parte com Co...","\r\nVistos, relatados e discutidos estes autos...",GAMAR

In [8]:
run_ner_pipeline_for_dataframe(
    df=df_processes,
    extractor=extractor_decisao_gpt4turbo,
    model_name="gpt-4-turbo",
    prompt_version="v1",
    run_id=datetime.now().strftime("Extração NER %d/%m/%Y %H:%M:%S")
)

# Obrigacao and Recomendacao Extraction

In [9]:
run_obrigacao_pipeline(extractor_obrigacao_gpt4turbo, extractor_responsible)

c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(
c:\Users\05911205424\Documents\Dev\decicontas.br\.venv\Lib\site-packages\langchain_openai\chat_models\base.py:1784: UserWarning: Cannot use method='json_schema' with model gpt-4 since it doesn't support OpenAI's Structured Output API. You can see supported models here: https://platform.openai.com/docs/guides/structured-outputs#supported-models. To fix this warning, set `method='function_calling'. Overriding to method='function_calling'.
  warnings.warn(

,id_ner_obrigacao,id_ner_decisao,ordem_obrigacao,descricao_obrigacao,id_processo,processo,orgao_responsavel,id_orgao_responsavel,monocratica,codigo_tipo_processo,...,interessado,orgao_origem,is_voto_divergente,id_voto_concordado,relatorio,fundamentacao_voto,conclusao,texto_acordao,setor_voto,responsaveis
0,67,327,0,expedição de determinação à autoridade compete...,541094,100693/2020,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,308,0,APO,...,LUCIA DE FATIMA FARIAS ...,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,False,NaN,1.\tTrata-se da apreciação de legalidade da co...,"6.\tInicialmente, assinalo que ainda não se op...","45.\tDiante do exposto, discordando do posicio...",\r\nDECIDEM os Conselheiros do Tribunal de Con...,GCAED,[{'nome_responsavel': 'LUCIA DE FATIMA FARIAS'...
1,68,327,1,expedição de determinação à autoridade compete...,541094,100693/2020,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,308,0,APO,...,LUCIA DE FATIMA FARIAS ...,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,False,NaN,1.\tTrata-se da apreciação de legalidade da co...,"6.\tInicialmente, assinalo que ainda não se op...","45.\tDiante do exposto, discordando do posicio...",\r\nDECIDEM os Conselheiros do Tribunal de Con...,GCAED,[{'nome_responsavel': 'LUCIA DE FATIMA FARIAS'...
2,69,327,2,"os gestores responsáveis, no prazo de 05 (cinc...",541094,100693/2020,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,308,0,APO,...,LUCIA DE FATIMA FARIAS ...,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,False,NaN,1.\tTrata-se da apreciação de legalidade da co...,"6.\tInicialmente, assinalo que ainda não se op...","45.\tDiante do exposto, discordando do posicio...",\r\nDECIDEM os Conselheiros do Tribunal de Con...,GCAED,[{'nome_responsavel': 'LUCIA DE FATIMA FARIAS'...
3,70,327,3,intimação do Instituto de Previdência dos Serv...,541094,100693/2020,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,308,0,APO,...,LUCIA DE FATIMA FARIAS ...,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,False,NaN,1.\tTrata-se da apreciação de legalidade da co...,"6.\tInicialmente, assinalo que ainda não se op...","45.\tDiante do exposto, discordando do posicio...",\r\nDECIDEM os Conselheiros do Tribunal de Con...,GCAED,[{'nome_responsavel': 'LUCIA DE FATIMA FARIAS'...
4,71,331,0,determinação para que a URBANA promova a publi...,550929,002489/2021,COMPANHIA DE SERVIÇOS URBANOS DE NATAL,554,0,REP,...,COMPANHIA DE SERVIÇOS URBANOS DE NATAL - URBAN...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,Trata-se de representação proposta pelo Minist...,"Com efeito, após a conclusão da instrução proc...","Ante ao exposto, em consonância integral com a...","Vistos, relatados e discutidos estes autos, A...",GCADE,"[{'nome_responsavel': 'ALVAMAR SILVA DO VALE',..."
5,72,331,1,estabeleço o prazo de 90 (noventa) dias para q...,550929,002489/2021,COMPANHIA DE SERVIÇOS URBANOS DE NATAL,554,0,REP,...,COMPANHIA DE SERVIÇOS URBANOS DE NATAL - URBAN...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,Trata-se de representação proposta pelo Minist...,"Com efeito, após a conclusão da instrução proc...","Ante ao exposto, em consonância integral com a...","Vistos, relatados e discutidos estes autos, A...",GCADE,"[{'nome_responsavel': 'ALVAMAR SILVA DO VALE',..."
6,73,338,0,"após o trânsito em julgado, abertura de feito ...",556805,004412/2021,PREFEITURA MUNICIPAL DE LAGOA DE VELHOS,410,0,REL,...,PREFEITURA MUNICIPAL DE LAGOA DE VELHOS ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,Autos instaurados em 12.nov.2021 (evento 0). V...,"Destaco, inicialmente, que o juiz natural para...","Com substrato no art. 61 da norma orgânica, so...","Vistos, relatados e discutidos estes autos, AC...",GAANA,[{'nome_responsavel': 'SONYARA DE SOUZA RIBEIR...
7,74,340,0,Determinar que o Prefeito Municipal de Santa M...,560871,000926/2022,PREFEITURA MUNICIPAL DE SANTA MARIA,470,0,ACO,...,PREFEITURA MUNICIPAL DE SANTA MARIA ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,1.\tTrata-se de Representação formulada pela D...,"8.\tImporta acentuar, inicialmente, que, nesse...","32.\tDiante do exposto, em harmonia com as raz...","Vistos, relatados e discutidos estes autos, AC...",GAMAR,[{'nome_responsavel': 'Prefeitura Municipal de...
8,75,340,1,Fixar prazo de 180 (cento e oitenta) dias corr...,560871,000926/2022,PREFEITURA MUNICIPAL DE SANTA MARIA,470,0,ACO,...,PREFEITURA MUNICIPAL DE SANTA MARIA ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,1.\tTrata-se de Representação formulada pela D...,"8.\tImporta acentuar, inicialmente, que, nesse...","32.\tDiante do exposto, em harmonia com as raz...","Vistos, relatados e discutidos estes autos, AC...",GAMAR,[{'nome_responsavel': 'Prefeitura Municipal de...
9,76,341,0,"NOTIFICAÇÃO, com fulcro no art. 45, II, da LCE...",613474,301794/2025,SECRETARIA MUNICIPAL DE SAÚDE DE NATAL,1276,0,DEN,...,JUSTIZ TERCEIRIZAÇÃO DE MÃO DE OBRA EIRELI ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,"Tratam os presentes autos de Comunicação, com ...","Inicialmente, esclareço que os presentes autos...","Diante do exposto, concordando em parte com Co...","\r\nVistos, relatados e discutidos estes autos...",GAMAR,[{'nome_responsavel': 'Victor Vinicius De Alme...
10,77,341,1,"CITAÇÃO da COOPMED, na figura de seu represent...",613474,301794/2025,SECRETARIA MUNICIPAL DE SAÚDE DE NATAL,1276,0,DEN,...,JUSTIZ TERCEIRIZAÇÃO DE MÃO DE OBRA EIRELI ...,TRIBUNAL DE CONTAS DO ESTADO,False,NaN,"Tratam os presentes autos de Comunicação, com ...","Inicialmente, esclareço que os presentes autos...","Diante do exposto, concordando em parte com Co...","\r\nVistos, relatados e discutidos estes autos...",GAMAR,[{'nome_responsavel': 'Victor Vinicius De Alme...

In [6]:
conn_processo = get_connection("BdDIP")

In [7]:
sql_nerdecisoes = """
SELECT * 
    FROM NERDecisao
"""
df_nerdecisoes = pd.read_sql(sql_nerdecisoes, conn_processo)

In [8]:
df_nerdecisoes

,IdNerDecisao,IdProcesso,IdComposicaoPauta,IdVotoPauta,Modelo,VersaoPrompt,RunId,RawJson,DataExtracao
0,1,599242,123668,46267,gpt-4-turbo,v1,Extração NER 04/12/2025 11:33:35,"{""multas"":[],""ressarcimentos"":[],""obrigacoes"":...",2025-12-04 14:33:37.259220
1,2,580147,123670,46294,gpt-4-turbo,v1,Extração NER 04/12/2025 11:33:35,"{""multas"":[],""ressarcimentos"":[],""obrigacoes"":...",2025-12-04 14:33:38.337366
2,3,364852,123489,45759,gpt-4-turbo,v1,Extração NER 04/12/2025 11:33:35,"{""multas"":[{""descricao_multa"":""CONHECIMENTO e ...",2025-12-04 14:33:41.478029
3,4,367272,123530,46107,gpt-4-turbo,v1,Extração NER 04/12/2025 11:33:35,"{""multas"":[],""ressarcimentos"":[],""obrigacoes"":...",2025-12-04 14:33:42.593977
4,5,446872,123660,45782,gpt-4-turbo,v1,Extração NER 04/12/2025 11:33:35,"{""multas"":[],""ressarcimentos"":[],""obrigacoes"":...",2025-12-04 14:33:43.609644
...,...,...,...,...,...,...,...,...,...
321,322,606751,124191,46800,gpt-4-turbo,v1,Extração NER 07/01/2026 13:50:35,"{""multas"":[],""ressarcimentos"":[],""obrigacoes"":...",2026-01-07 16:52:44.419538
322,323,612222,123901,46539,gpt-4-turbo,v1,Extração NER 07/01/2026 13:50:35,"{""multas"":[],""ressarcimentos"":[],""obrigacoes"":...",2026-01-07 16:52:45.739376
323,324,612469,124087,46658,gpt-4-turbo,v1,Extração NER 07/01/2026 13:50:35,"{""multas"":[],""ressarcimentos"":[],""obrigacoes"":...",2026-01-07 16:52:49.454578
324,325,617115,124106,46712,gpt-4-turbo,v1,Extração NER 07/01/2026 13:50:35,"{""multas"":[],""ressarcimentos"":[],""obrigacoes"":...",2026-01-07 16:52:57.450217
325,326,617990,124093,46459,gpt-4-turbo,v1,Extração NER 07/01/2026 13:50:35,"{""multas"":[],""ressarcimentos"":[],""obrigacoes"":...",2026-01-07 16:52:59.164762

In [9]:
sql_obrigacao_processar = """
SELECT 
    o.IdNerObrigacao,
    o.IdNerDecisao,
    o.Ordem,
    o.DescricaoObrigacao,
    d.IdProcesso,
    CONCAT(p.Numero_Processo, '/', p.Ano_Processo) AS processo,
    org.Nome AS orgao_responsavel,
    org.IdOrgao AS id_orgao_responsavel,
    gp.TipoPessoa AS tipo_responsavel,
    gp.IdPessoa AS id_pessoa
FROM BdDIP.dbo.NERObrigacao o
INNER JOIN BdDIP.dbo.NERDecisao d 
    ON d.IdNerDecisao = o.IdNerDecisao
INNER JOIN processo.dbo.Processos p
    ON p.IdProcesso = d.IdProcesso
INNER JOIN processo.dbo.Orgaos org 
    ON p.IdOrgaoEnvolvido = org.IdOrgao 
INNER JOIN processo.dbo.Pro_ProcessosResponsavelDespesa pprd 
    ON pprd.IdProcesso = p.IdProcesso 
INNER JOIN processo.dbo.GenPessoa gp 
    ON gp.IdPessoa = pprd.IdPessoa 
LEFT JOIN BdDIP.dbo.ObrigacaoProcessada op
    ON op.IdNerObrigacao = o.IdNerObrigacao
WHERE op.IdObrigacaoProcessada IS NULL;
"""

df_obrigacao_processar = pd.read_sql(sql_obrigacao_processar, conn_processo)

In [10]:
sql_recomendacao_processar = """
SELECT 
    r.IdNerRecomendacao,
    r.IdNerDecisao,
    r.Ordem,
    r.DescricaoRecomendacao,
    d.IdProcesso,
    CONCAT(p.Numero_Processo, '/', p.Ano_Processo) AS processo,
    org.Nome AS orgao_responsavel,
    org.IdOrgao AS id_orgao_responsavel,
    gp.Nome AS nome_responsavel,
    gp.Documento AS documento_responsavel,
    gp.TipoPessoa AS tipo_responsavel,
    gp.IdPessoa AS id_pessoa
FROM BdDIP.dbo.NERRecomendacao r
INNER JOIN BdDIP.dbo.NERDecisao d 
    ON d.IdNerDecisao = r.IdNerDecisao
INNER JOIN processo.dbo.Processos p
    ON p.IdProcesso = d.IdProcesso
INNER JOIN processo.dbo.Orgaos org 
    ON p.IdOrgaoEnvolvido = org.IdOrgao 
INNER JOIN processo.dbo.Pro_ProcessosResponsavelDespesa pprd 
    ON pprd.IdProcesso = p.IdProcesso 
INNER JOIN processo.dbo.GenPessoa gp 
    ON gp.IdPessoa = pprd.IdPessoa 
LEFT JOIN BdDIP.dbo.RecomendacaoProcessada rp
    ON rp.IdNerRecomendacao = r.IdNerRecomendacao
WHERE rp.IdRecomendacaoProcessada IS NULL;
"""

df_recomendacao_processar = pd.read_sql(sql_recomendacao_processar, conn_processo)

In [12]:
len(df_obrigacao_processar)

166

In [13]:
len(df_recomendacao_processar)

73